import Head from 'next/head';
import { useMemo } from 'react';

import { getLibraries } from '@/lib/tmdb';
import constants from '@/lib/constants';
import TopMenu from '@/components/top-menu';
import Footer from '@/components/footer';
import TMDBContext from '@/contexts/tmdb-context';
import DiscoverList from '@/components/discover-list';
import Carousel from '@/components/carousel';

export default function Home({ movies, baseUrl, apiKey }) {
  const tmdb = useMemo(() => ({ apiKey, baseUrl }), [baseUrl, apiKey]);

  return (
    <TMDBContext.Provider value={tmdb}>
      <Head>
        <title>Moovie Time - Perqara</title>
        <meta name="description" content="Generated by create next app for Perqara" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-moovie-background">
        <TopMenu baseUrl={baseUrl} />
        <main className="flex flex-col">
          <Carousel movies={movies} />
          <DiscoverList movies={movies} />
        </main>
        <footer>
          <Footer />
        </footer>
      </div>
    </TMDBContext.Provider>
  );
}

export async function getServerSideProps({ query }) {
  const { sortBy } = query;
  const baseUrl = constants.TMDB_BASE_URL;
  const apiKey = constants.TMDB_API_KEY;
  const movies = await getLibraries({ sortBy });

  return {
    props: {
      movies,
      baseUrl,
      apiKey,
    },
  };
}
