import Head from 'next/head';
import { getLibraries } from '@/lib/tmdb';
import TopMenu from '@/components/top-menu';
import MovieItem from '@/components/movie-item';
import Footer from '@/components/footer';
import constants from '@/lib/constants';
import TMDBContext from '@/contexts/tmdb-context';
import { useMemo } from 'react';

export default function Home({ movies, baseUrl, apiKey }) {
  const tmdb = useMemo(() => ({ apiKey, baseUrl }), [baseUrl, apiKey]);

  return (
    <TMDBContext.Provider value={tmdb}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-moovie-background">
        <TopMenu baseUrl={baseUrl} />
        <main className="relative my-28">
          <div className="grid grid-cols-5 gap-x-6 gap-y-8 px-32">
            {movies.results.map((movie) => <MovieItem key={movie.title} {...movie} />)}
          </div>
        </main>
        <footer>
          <Footer />
        </footer>
      </div>
    </TMDBContext.Provider>
  );
}

export async function getServerSideProps() {
  const baseUrl = constants.TMDB_BASE_URL;
  const apiKey = constants.TMDB_API_KEY;
  const movies = await getLibraries();

  return {
    props: {
      movies,
      baseUrl,
      apiKey,
    },
  };
}
